// Maps each episode's scenes to a generated illustration file in
// public/images/, one per scene, in order. These were generated by the
// project owner on their own device (Bing Image Creator) from prompts
// derived from each scene's `visual` field, and uploaded — not produced
// inside this sandbox, since AI image generation here would require
// enabling real Google Cloud billing (see README "Video pipeline").
// Add an entry here whenever a new episode gets its illustrations.
export const SCENE_IMAGES: Record<string, string[]> = {
  "1": [
    "images/scene-1.png",
    "images/scene-2.jpg",
    "images/scene-3.jpg",
    "images/scene-4.jpg",
    "images/scene-5.jpg",
    "images/scene-6.jpg",
    "images/scene-7.jpg",
  ],
};
